apiVersion: v1
kind: Service
metadata:
  name: gateways-service
  labels:
    name: gateways-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30072
      name: gateways-port
  selector:
    app: gateways
  type: NodePort 

